name: h4d_env
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - attrs=19.1.0
  - autopep8
  - backcall=0.1.0
  - black
  - blas
  - bleach=3.1.0
  - bzip2=1.0.6
  - ca-certificates=2019.1.23
  - cairo=1.16.0
  - certifi=2019.3.9
  - cffi=1.12.3
  - click=7.0
  - cloudpickle=1.0.0
  - cudatoolkit=10.0.130
  - cycler=0.10.0
  - cython
  - cytoolz=0.9.0.1
  - dask-core=1.2.2
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - easydict=1.9
  - entrypoints=0.3
  - expat=2.2.5
  - ffmpeg=4.1.3
  - flake8
  - fontconfig=2.13.1
  - freetype=2.9.1
  - gettext=0.19.8.1
  - giflib
  - gitpython
  - glib=2.58.3
  - gmp=6.1.2
  - gnutls=3.6.5
  - graphite2=1.3.13
  - gst-plugins-base=1.14.4
  - gstreamer=1.14.4
  - h5py=2.9.0
  - harfbuzz=2.4.0
  - hdf5=1.10.4
  - icu=58.2
  - imageio=2.5.0
  - intel-openmp=2019.3
  - ipykernel=5.*
  - ipython=7.*
  - ipython_genutils=0.2.*
  - isort
  - jasper=1.900.1
  - jedi=0.13.3
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9c
  - jsonschema=3.0.1
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - kiwisolver=1.1.0
  - lame=3.100
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libiconv=1.15
  - liblapack=3.8.0
  - liblapacke=3.8.0
  - libopenblas=0.3.6
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - libuuid=2.32.1
  - libwebp=1.0.2
  - libxcb=1.13
  - libxml2=2.9.9
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - matplotlib-base=3.1.0
  - mistune=0.8.4
  - mkl=2019.3
  - mkl_fft=1.0.13
  - mkl_random=1.0.4
  - mypy
  - nbconvert
  - nbformat
  - ncurses=6.1
  - nettle=3.4.1
  - networkx=2.3
  - ninja=1.9.0
  - nomkl=3.0
  - notebook=5.7.8
  - numba
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openblas
  - openblas-devel
  - opencv=4.1.0
  - openh264=1.8.0
  - openssl=1.1.1
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.4.0
  - pcre=8.41
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.1.1
  - pixman=0.34.0
  - progress
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - pycparser=2.19
  - pygments=2.4.0
  - pylint
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - pytest
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytorch=1.1.0
  - pytz=2019.1
  - pywavelets=1.0.3
  - pyyaml=5.1
  - pyzmq=18.0.0
  - qt=5.9.7
  - readline=7.0
  - rope
  - scikit-image
  - scikit-learn
  - scipy=1.3.0
  - send2trash=1.5.0
  - setproctitle=1.1.10
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.28.0
  - tensorboard=1.13.1
  - tensorboardx=1.7
  - tensorflow-gpu=1.13.1
  - terminado=0.8.2
  - terminaltables=3.1.0
  - testpath=0.4.2
  - tk=8.6.9
  - toolz=0.9.0
  - torchvision=0.3.0
  - tornado=6.0.2
  - tqdm
  - traitlets=4.3.2
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - x264=1!152.20180806
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.9
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.7
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yacs
  - yaml=0.1.7
  - zeromq=4.3.1
  - zlib=1.2.11
  - zstd=1.3.7
