name: h4d_centernet
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - autopep8
  - black
  - click
  - cudatoolkit=10.0
  - cython
  - easydict
  - flake8
  - gitpython
  - h5py
  - hdf5
  - imageio
  - ipykernel=5.*
  - ipython=7.*
  - ipython_genutils=0.2.*
  - isort
  - jedi
  - jupyter_client
  - jupyter_core
  - jupyterlab
  - jupyterlab_server
  - matplotlib
  - mypy
  - nbconvert
  - nbformat
  - numba
  - numpy
  - opencv
  - pandoc
  - pillow
  - pip
  - progress
  - pygments
  - pylint
  - pytest
  - python=3.7.3
  - pytorch=1.1
  - scikit-image
  - scikit-learn
  - scipy
  - setproctitle
  - setuptools
  - tensorboard
  - tensorboardx
  - tensorflow-gpu
  - torchvision
  - tqdm
  - yacs
  - yaml
