MODEL:
  NUM_CLASSES: 36
  BACKBONE:
    OUT_CHANNELS: (512, 1024, 512, 256, 256, 256, 256)
    EXTRAS: [256, 'S', 512, 128, 'S', 256, 128, 'S', 256, 128, 'S', 256]
  PRIORS:
    FEATURE_MAPS: [64, 32, 16, 8, 4, 2, 1]
    STRIDES: [8, 16, 32, 64, 128, 256, 512]
    MIN_SIZES: [20.48, 51.2, 133.12, 215.04, 296.96, 378.88, 460.8]
    MAX_SIZES: [51.2, 133.12, 215.04, 296.96, 378.88, 460.8, 542.72]
    ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2, 3], [2], [2]]
    BOXES_PER_LOCATION: [4, 6, 6, 6, 6, 4, 4]
  BOX_HEAD:
    PREDICTOR: "SSDSigmaBoxPredictor"
INPUT:
  IMAGE_SIZE: 512
DATASETS:
  TRAIN: ("xview_coco_v2_train", )
  TEST: ("xview_coco_v2_val", )
SOLVER:
  MAX_ITER: 1200000
  LR_STEPS: [360000, 480000]
  GAMMA: 0.1
  BATCH_SIZE: 24
  LR: 1e-3

OUTPUT_DIR: "outputs/output_vgg_ssd512_xview_coco"
