MODEL:
  NUM_CLASSES: 36
  PRIORS:
    FEATURE_MAPS: [38, 19, 10, 5, 3, 1]
    STRIDES: [8, 16, 32, 64, 100, 300]
    MIN_SIZES: [21, 45, 99, 153, 207, 261]
    MAX_SIZES: [45, 99, 153, 207, 261, 315]
    ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2], [2]]
    BOXES_PER_LOCATION: [4, 6, 6, 6, 4, 4]
  BOX_HEAD:
    NAME: "SSDBoxHead"
    PREDICTOR: "SSDSigmaBoxPredictor"
INPUT:
  IMAGE_SIZE: 300
DATASETS:
  TRAIN: ("xview_coco_v2_tiny_train", )
  TEST: ("xview_coco_v2_tiny_val", )
SOLVER:
  MAX_ITER: 400000
  LR_STEPS: [280000, 360000]
  GAMMA: 0.1
  BATCH_SIZE: 48
  LR: 1e-3

OUTPUT_DIR: "outputs/output_vgg_ssd300_xview_coco"